
INSERT INTO FLIGHT_SCHEDULE (FLIGHT_NUMBER, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME)
    VALUES ('EK 501', 'BOM', 'DXB', PARSEDATETIME('4:30', 'HH:mm'), PARSEDATETIME('6:00', 'HH:mm'));

INSERT INTO FLIGHT_SCHEDULE (FLIGHT_NUMBER, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME)
    VALUES ('EK 2137', 'BOM', 'DXB', PARSEDATETIME('05:10', 'HH:mm'), PARSEDATETIME('06:50', 'HH:mm'));

INSERT INTO FLIGHT_SCHEDULE (FLIGHT_NUMBER, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME)
    VALUES ('EK 507', 'BOM', 'DXB', PARSEDATETIME('15:35', 'HH:mm'), PARSEDATETIME('17:20', 'HH:mm'));

INSERT INTO FLIGHT_SCHEDULE (FLIGHT_NUMBER, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME)
    VALUES ('EK 503', 'BOM', 'DXB', PARSEDATETIME('19:20', 'HH:mm'), PARSEDATETIME('21:00', 'HH:mm'));

INSERT INTO FLIGHT_SCHEDULE (FLIGHT_NUMBER, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME)
    VALUES ('EK 201', 'DXB', 'JFK', PARSEDATETIME('08:30', 'HH:mm'), PARSEDATETIME('14:25', 'HH:mm'));

INSERT INTO FLIGHT_SCHEDULE (FLIGHT_NUMBER, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME)
    VALUES ('EK 203', 'DXB', 'JFK', PARSEDATETIME('02:50', 'HH:mm'), PARSEDATETIME('08:50', 'HH:mm'));

INSERT INTO FLIGHT_SCHEDULE (FLIGHT_NUMBER, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME)
    VALUES ('EK 205', 'DXB', 'JFK', PARSEDATETIME('09:45', 'HH:mm'), PARSEDATETIME('19:00', 'HH:mm'));

INSERT INTO FLIGHT_SCHEDULE (FLIGHT_NUMBER, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME)
    VALUES ('EK 211', 'DXB', 'IAH', PARSEDATETIME('09:35', 'HH:mm'), PARSEDATETIME('16:50', 'HH:mm'));