server:
  port: 9999

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
      routes:
      - id: az-master-data-service
        uri: http://localhost:8084
        predicates:
        - Path=/api/airport/**

      - id: az-flight-connector-builder-service
        uri: http://localhost:8083
        predicates:
        - Path=/api/flight/**