
INSERT INTO AIRPORT (AIRPORT_CODE, AIRPORT_NAME, CITY_NAME, COORDINATES) VALUES ('BOM', 'Chhatrapati Shivaji Maharaj International Airport', 'Mumbai', '19°05′19″N 72°52′05″E');
INSERT INTO AIRPORT (AIRPORT_CODE, AIRPORT_NAME, CITY_NAME, COORDINATES) VALUES ('DXB', 'Dubai Internation Airport', 'Dubai', '25°15′10″N 055°21′52″E');
INSERT INTO AIRPORT (AIRPORT_CODE, AIRPORT_NAME, CITY_NAME, COORDINATES) VALUES ('JFK', 'Jhon F Kennedy Airport', 'New York', '40°38′23″N 073°46′44″W');
INSERT INTO AIRPORT (AIRPORT_CODE, AIRPORT_NAME, CITY_NAME, COORDINATES) VALUES ('IAH', 'George Bush International Airport', 'Houston', '29°59′04″N 095°20′29″W');